### ISSUE TITLE
[Feature Request] Python 3 Compatibility

### ISSUE THREAD

**Issue by stimpy2318** [Salandora/OctoPrint-EEPROM-Repetier#11]
Please add Python 3 Compatibility as outlined [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html).

**Comment by lmcbmai** [comment]
I am not a developer, but looks like the plugin itself is compatible with Python 3 and just missing 
`__plugin_pythoncompat__ = ">=2.7,<4"`
after 
`__plugin_name__ = "EEPROM Repetier Editor Plugin" `
in `__init__.py` file.

Was able to install it in OctoPrint 1.4.2/Python 3.7.3 using Plugin Manager's "**... from an uploaded archive**" option and so far it works without issues.

**Comment by Wotsamatter** [comment]
Upgrade to plugin version 0.1.3
