### ISSUE TITLE
Values are not saved in Repetier EEPROM - Melzi Board

### ISSUE THREAD

**Issue by malebuffy** [Salandora/OctoPrint-EEPROM-Repetier#3]
Hello,

The Plugin Recognizes my Firmware and reads everything OK. When I try to change something and press save, even after issuing a M500 command from the Terminal window, when I load the EEPROM Values again, the Values haven't changed and stayed the same. 

Writing from Repetier Host however, works everytime. 

Using a Raspberry Pi 2 B with  OctoPi image.

**Comment by Salandora** [comment]
Can you please provide the Terminal output it would even be better to have a full serial.log.
Also please check the JavaScript console for errors.

**Comment by malebuffy** [comment]
Well it seems like Java was the problem on my machine. I realised whenever it was trying to run, java crashed, so it never send any data to the EEPROM. However there was no error message on the Plugin.

Thanks for the tip.
