### ISSUE TITLE
Does not see my Rostock Max V2 with a ramb0 running Repetier 9.15

### ISSUE THREAD

**Issue by dbfrompw** [Salandora/OctoPrint-EEPROM-Repetier#4]

**Comment by Salandora** [comment]
No informations no help! 
Add screens, add logs, until then closed.

**Comment by dbfrompw** [comment]
What more do you want?? It does not see it as a Repetier. Plan and simple. It does not work on my ramb0 board.

**Comment by Salandora** [comment]
E.g. Javascript console log, terminal output.
