### ISSUE TITLE
possible feature request? option to be a tab (or a version of this plugin that loads as a tab)

### ISSUE THREAD

**Issue by ntoff** [Salandora/OctoPrint-EEPROM-Repetier#5]
Out of curiosity, how hard would it be to make it an option to have the firmware editor show up as a tab (in  the terminal and temperature and control section)? Or if that's not optionable, a tab version of this plugin?

**Comment by Salandora** [comment]
Shouldn't be to hard, basically you would need to change the line 23 in __init__.py:
  
  dict(type="settings", template="eeprom_repetier_settings.jinja2", custom_bindings=True)
  
to:
  
  dict(type="tab", template="eeprom_repetier_tab.jinja2", custom_bindings=True)
  
and also rename the eeprom_repetier_settings.jinja2 to eeprom_repetier_tab.jinja2

It should be easy to make this as an optional feature.
do you like to tackle this? 
I do not have the time right now.
And I'm sure I'll not have time until, uhm ..., Christmas next year?

**Comment by ntoff** [comment]
Yeah I'll take a stab at it, thanks for the tip.

**Comment by Salandora** [comment]
Alright have assigned you to this ticket, would be nice if you would make a PR for it if you make it a switchable thing.

**Comment by ntoff** [comment]
hmm, it might take me a while too. I tried just switching it to a tab and it doesn't pick up repetier as the firmware and (unrelated to this) whenever I open my computer it takes forever for C drive to come up so I think the hard drive is dead. Looks like I'm up for a new hard drive and a reinstall.

I'll keep picking away at it in my spare time though if I can, for as long as my spare PC holds up and to the best of my (still learning on the fly) abilities.

**Comment by Salandora** [comment]
No problem I believe this is not a critical feature everyone wants to have, so take your time.

**Comment by ntoff** [comment]
Ok, I've got it working as a tab and a little bit of work on detecting the current tab / if the tab is changed to the eeprom tab and automatically loading the eeprom values but I disabled that (left code in, just commented out) since constant tab changes might negatively impact print performance, will have to test that some time but otherwise that works too.

https://github.com/ntoff/OctoPrint-EEPROM-Repetier/commit/97712f76759e154291089492dca5ac06df70dd93

I agree it's probably not a feature anyone will ever want besides probably me and might actually be better off left only in the settings to prevent accidental changes if someone accidentally clicks on the tab and their cat walks on the keyboard or something. At least if it's buried in the settings page you have to deliberately go to it to change something.

**Comment by ntoff** [comment]
I think this issue is worth closing, there's been no other interest in it, do you agree it should be closed?

**Comment by Salandora** [comment]
Well I guess you're right.
Closing it therefore :-)
