### ISSUE TITLE
Problem with EEPROM access

### ISSUE THREAD

**Issue by McKaNaN** [Salandora/OctoPrint-EEPROM-Repetier#8]
I had had problem for enter in EEPROM Repetier for Anet A8.

OctoPrint show me this message:

**EEprom Repetier Plugin**

This plugin is designed to get, change and save the values in the Eeprom of your Repetier Firmware based Machine.
Your machine is not Repetier Firmware based

But... I use Anet A8 with serial motherboard and Skynet 2.3.1.

Can you help me please?
<img width="966" alt="captura de pantalla 2017-07-30 a las 1 36 29" src="https://user-images.githubusercontent.com/26546335/28749441-8cfe1e9a-74c7-11e7-9538-430f20f46ffa.png">

**Comment by Salandora** [comment]
Skynet is Marlin firmware based, 
You should use this instead: http://plugins.octoprint.org/plugins/eeprom_marlin/
